const smoothiesData = [
    { id: 1, name: 'orange', price: '0.5L 20$', category: 'fruit', image: '../static/images/1.jpeg' },
  { id: 2, name: 'Strawberry', price: '0.5L 20$', category: 'fruit', image: '../static/images/27.jpeg' },
  { id: 3, name: 'Blueberry', price: '0.5L 20$', category: 'fruit', image: '../static/images/3.jpeg' },
  { id: 4, name: 'Kale', price: '0.5L 20$', category: 'fruit', image: '../static/images/4.jpeg' },
  { id: 5, name: 'Mango', price: '0.5L 20$', category: 'fruit', image: '../static/images/5.jpeg' },
  { id: 6, name: 'Pineapple', price: '0.5L 20$', category: 'fruit', image: '../static/images/6.jpeg' },
  { id: 7, name: 'Spinach', price: '0.5L 20$', category: 'fruit', image: '../static/images/7.jpeg' },
  { id: 8, name: 'Kale', price: '0.5L 20$', category: 'fruit', image: '../static/images/8.jpeg' },
  { id: 9, name: 'Almond Milk', price: '0.5L 20$', category: 'fruit', image: '../static/images/9.jpeg' },
  { id: 10, name: 'Coconut Water', price: '0.5L 20$', category: 'fruit', image: '../static/images/10.jpeg' },
  { id: 11, name: 'Apple', price: '0.5L 20$', category: 'fruit', image: '../static/images/11.jpeg' },
  { id: 12, name: 'Grape', price: '0.5L 20$', category: 'fruit', image: '../static/images/12.jpeg' },
  { id: 13, name: 'Cherry', price: '0.5L 20$', category: 'fruit', image: '../static/images/13.jpeg' },
  { id: 14, name: 'Lemon', price: '0.5L 20$', category: 'fruit', image: '../static/images/14.jpeg' },
  { id: 15, name: 'Papaya', price: '0.5L 20$', category: 'fruit', image: '../static/images/15.jpeg' },
  { id: 16, name: 'Avocado', price: '0.5L 20$', category: 'fruit', image: '../static/images/16.jpeg' },
  { id: 17, name: 'Celery', price: '0.5L 20$', category: 'fruit', image: '../static/images/17.jpeg' },
  { id: 18, name: 'Strawberry', price: '0.5L 20$', category: 'fruit', image: '../static/images/18.jpeg' },
  { id: 19, name: 'Carrot', price: '0.5L 20$', category: 'fruit', image: '../static/images/19.jpeg' },
  { id: 20, name: 'Soy Milk', price: '0.5L 20$', category: 'fruit', image: '../static/images/20.jpeg' },
  { id: 1, name: 'Banana', price: '0.5L 20$', category: 'fruit', image: '../static/images/21.jpeg' },
  { id: 2, name: 'Strawberry', price: '0.5L 20$', category: 'fruit', image: '../static/images/22.jpeg' },
  { id: 3, name: 'Blueberry', price: '0.5L 20$', category: 'fruit', image: '../static/images/23.jpeg' },
  { id: 4, name: 'Orange', price: '0.5L 20$', category: 'fruit', image: '../static/images/24.jpeg' },
  { id: 5, name: 'Mango', price: '0.5L 20$', category: 'fruit', image: '../static/images/25.jpeg' },
  { id: 6, name: 'Pineapple', price: '0.5L 20$', category: 'fruit', image: '../static/images/26.jpeg' },
 
];

  export default smoothiesData;