const smoothiesData = [
    { id: 1, name: 'Banana', price: 0.5, category: 'fruit', image: 'https://placekitten.com/100/100' },
  { id: 2, name: 'Strawberry', price: 0.7, category: 'fruit', image: 'https://placekitten.com/100/101' },
  { id: 3, name: 'Blueberry', price: 0.9, category: 'fruit', image: 'https://placekitten.com/100/102' },
  { id: 4, name: 'Orange', price: 0.4, category: 'fruit', image: 'https://placekitten.com/100/103' },
  { id: 5, name: 'Mango', price: 1.0, category: 'fruit', image: 'https://placekitten.com/100/104' },
  { id: 6, name: 'Pineapple', price: 1.2, category: 'fruit', image: 'https://placekitten.com/100/105' },
  { id: 7, name: 'Spinach', price: 0.8, category: 'vegetable', image: 'https://placekitten.com/100/106' },
  { id: 8, name: 'Kale', price: 0.6, category: 'vegetable', image: 'https://placekitten.com/100/107' },
  { id: 9, name: 'Almond Milk', price: 0.3, category: 'liquid', image: 'https://placekitten.com/100/108' },
  { id: 10, name: 'Coconut Water', price: 0.5, category: 'liquid', image: 'https://placekitten.com/100/109' },
  { id: 11, name: 'Apple', price: 0.4, category: 'fruit', image: 'https://placekitten.com/100/110' },
  { id: 12, name: 'Grape', price: 0.8, category: 'fruit', image: 'https://placekitten.com/100/111' },
  { id: 13, name: 'Cherry', price: 0.6, category: 'fruit', image: 'https://placekitten.com/100/112' },
  { id: 14, name: 'Lemon', price: 0.4, category: 'fruit', image: 'https://placekitten.com/100/113' },
  { id: 15, name: 'Papaya', price: 1.0, category: 'fruit', image: 'https://placekitten.com/100/114' },
  { id: 16, name: 'Avocado', price: 1.2, category: 'fruit', image: 'https://placekitten.com/100/115' },
  { id: 17, name: 'Celery', price: 0.7, category: 'vegetable', image: 'https://placekitten.com/100/116' },
  { id: 18, name: 'Beetroot', price: 0.9, category: 'vegetable', image: 'https://placekitten.com/100/117' },
  { id: 19, name: 'Carrot', price: 0.4, category: 'vegetable', image: 'https://placekitten.com/100/118' },
  { id: 20, name: 'Soy Milk', price: 0.6, category: 'liquid', image: 'https://placekitten.com/100/119' },
  { id: 1, name: 'Banana', price: 0.5, category: 'fruit', image: 'https://placekitten.com/100/100' },
  { id: 2, name: 'Strawberry', price: 0.7, category: 'fruit', image: 'https://placekitten.com/100/101' },
  { id: 3, name: 'Blueberry', price: 0.9, category: 'fruit', image: 'https://placekitten.com/100/102' },
  { id: 4, name: 'Orange', price: 0.4, category: 'fruit', image: 'https://placekitten.com/100/103' },
  { id: 5, name: 'Mango', price: 1.0, category: 'fruit', image: 'https://placekitten.com/100/104' },
  { id: 6, name: 'Pineapple', price: 1.2, category: 'fruit', image: 'https://placekitten.com/100/105' },
 
];

  export default smoothiesData;